Add datadog node template
aws/aws-sam-cli-app-templates pull request #191
Opened 2022-02-16 18:34 UTC by thedavlee

*Issue #, if available:*

*Description of changes:*
- Added "Monitoring and Observability with Datadog" template for nodejs14

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-02-16 19:16 UTC, maxday commented on nodejs14.x/cookiecutter-aws-sam-hello-nodejs-datadog/.gitignore
> +
I think we can clean this?

2022-02-16 19:18 UTC, maxday commented on nodejs14.x/cookiecutter-aws-sam-hello-nodejs-datadog/{{cookiecutter.project_name}}/.gitignore
> +
same here

2022-02-16 19:50 UTC, maxday commented on .gitignore
> +.gradle/
do we need to modify this main .gitignore file?

2022-02-16 20:03 UTC, maxday commented on nodejs14.x/cookiecutter-aws-sam-hello-nodejs-datadog/{{cookiecutter.project_name}}/hello-world/tests/unit/test-handler.js
> +        // expect(response.location).to.be.an("string");
are those comments intentional?

2022-05-12 01:51 UTC, mndeveci requested changes

2022-05-12 01:51 UTC, mndeveci commented on manifest.json
> +    {
Can you remove changes to this file, as the `__comment__` suggest?

2022-05-12 01:51 UTC, mndeveci commented on nodejs14.x/cookiecutter-aws-sam-hello-nodejs-datadog/{{cookiecutter.project_name}}/hello-world/package.json
> +  "repository": "https://github.com/awslabs/aws-sam-cli/tree/develop/samcli/local/init/templates/cookiecutter-aws-sam-hello-nodejs",
nit: can you update the repository link here?

2022-06-29 04:19 UTC, hawflau requested changes

2022-06-29 04:19 UTC, hawflau commented on manifest.json
> +    {
Please remove the changes in this file from the PR. We have frozen this file and won't accept any change in this file.

2022-08-22 19:57 UTC, jfuss commented
Closing given no response. Feel free to handle feedback and re-open or create a new PR.

2022-08-22 19:57 UTC, closed without merging