Added SAM init Connector templates
aws/aws-sam-cli-app-templates pull request #291
Opened 2022-10-07 19:16 UTC by GavinZZ

*Issue #, if available:*

*Description of changes:*
Serverless Connector is just released. Implemented some examples for customers to use.
For more detail on serverless connector, https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/managing-permissions-connectors.html

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-10-07 19:57 UTC, hoffa commented on nodejs12.x/cookiecutter-aws-sam-step-functions-with-connectors/{{cookiecutter.project_name}}/template.yaml
> +        - Write
Consistent with the other resources in the template:

```suggestion
  SfnToStockCheckerFunctionConnector:
    Type: AWS::Serverless::Connector # More info about Connector Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-connector.html
    Properties:
      Source:
        Id: StockTradingStateMachine
      Destination:
        Id: StockCheckerFunction
      Permissions:
        - Write
```

2022-10-07 21:11 UTC, hoffa commented on nodejs12.x/cookiecutter-aws-sam-step-functions-with-connectors/{{cookiecutter.project_name}}/template.yaml
> +    Type: AWS::Serverless::Connector # More info about Connector Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-connector.html
nit: other resources only include this comment for the first instance

2022-10-07 21:11 UTC, hoffa approved these changes

2022-10-07 22:03 UTC, hawflau requested changes
Can we add some tests under https://github.com/aws/aws-sam-cli-app-templates/tree/master/tests/integration?

2022-10-07 22:06 UTC, GavinZZ commented
> Can we add some tests under https://github.com/aws/aws-sam-cli-app-templates/tree/master/tests/integration?

Oh nice, didn't realize there's tests here. Will do that.

2022-10-11 18:06 UTC, GavinZZ commented
Ran the new unit/integ tests with `pytest tests/* -k connector`. All passed.
<img width="1200" alt="Screen Shot 2022-10-11 at 11 06 08 AM" src="https://user-images.githubusercontent.com/28763956/195166700-448337af-acc1-475f-98ff-e62fc0d67cf2.png">

2022-10-11 18:09 UTC, hawflau approved these changes

2022-10-12 18:00 UTC, awood45 approved these changes

2022-10-12 20:54 UTC, merged