feat: AWS Lambda Powertools for Java templates
aws/aws-sam-cli-app-templates pull request #338
Opened 2023-02-02 16:26 UTC by am29d

*Issue #, if available:* #337 

*Description of changes:*

Creating three new templates for runtimes java8, java8.al2 and java11, for maven and gradle build tool respectively. These include allowing customers to selectively add AWS Lambda Powertools Tracing, Logging and Metrics utilities.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-02-03 08:52 UTC, am29d commented
I checked the error logs from the last CodeBuild run and there seems to be some issue with Gradle:
> Stdout: Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

I added integration tests for the folders, and if I run the same command as the CI they are green. Is there a specific configuration on the CI server that I need to replicate on my local machine?

2023-02-07 17:10 UTC, jfuss requested changes
Some small requests. I assume these were validated in some way (probably tests?), because it's hard to follow with all the cookiecutter ifs and such.

2023-02-08 09:13 UTC, am29d commented on nodejs14.x/hello-ts-pt/cookiecutter.json
> +    "Powertools Tracing": ["enabled","disabled"],
This was an accident, will scope it only for Java.

2023-02-08 09:48 UTC, am29d commented
> Some small requests. I assume these were validated in some way (probably tests?), because it's hard to follow with all the cookiecutter ifs and such.

I have validated all 6 templates manually. I have added the unit tests, similar what we already have for other projects.

2023-02-10 12:10 UTC, am29d commented on tests/integration/unit_test/test_unit_test_java11.py
> +    directory = "java11/hello-powertools-gradle"
Completely forgot about the tests, sorry 🤦‍♂️

2023-02-14 22:25 UTC, lucashuy commented
Was not able to reproduce the Java 11 unit test failures by running the test on my local system, I'll merge from master to kick off the codebuild again to see if this is still a problem.

2023-02-24 17:37 UTC, heitorlessa commented
@am29d could you remove Gradle from this template so we can merge it? I'll remove from the docs too

2023-02-26 13:24 UTC, am29d commented
I see you opened the PR without gradle, so I am closing this PR

2023-02-26 13:24 UTC, closed without merging