chore: rename Lambda Powertools
aws/aws-sam-cli-app-templates pull request #422
Opened 2023-05-24 13:14 UTC by sthulb

*Issue #, if available:*

*Description of changes:*
Finds Powertools references and replaces it with Powertools for AWS Lambda (<language>)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-05-24 16:58 UTC, jfuss approved these changes

2023-05-25 01:01 UTC, moelasmar approved these changes

2023-05-25 01:02 UTC, moelasmar requested changes
Could you please check the failing approval jobs

2023-05-25 09:42 UTC, sthulb commented
> Could you please check the failing approval jobs

yep. I'll get it on it today.

2023-05-25 17:42 UTC, moelasmar approved these changes

2023-05-27 19:43 UTC, merged