feat: add ruby3.3 support
aws/aws-sam-cli-app-templates pull request #494
Opened 2024-03-20 16:20 UTC by hawflau

*Issue #, if available:*

*Description of changes:*
Adding Ruby3.3 App Templates

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-03-20 17:08 UTC, mndeveci approved these changes

2024-03-20 17:10 UTC, mndeveci requested changes
We need to update CI configuration as well; https://github.com/aws/aws-sam-cli-app-templates/blob/master/.github/workflows/build_test_invoke.yml#L223-L253

2024-03-27 17:51 UTC, mndeveci approved these changes
Changes looking good! The CI checks should be passing once we have SAM CLI changes in as well as the production lambda image

2024-04-02 22:12 UTC, hnnasit approved these changes

2024-04-03 02:39 UTC, merged