Stack integration test for Node 12 templates
aws/aws-sam-cli-app-templates pull request #79
Opened 2020-12-22 21:17 UTC by aahung

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-12-23 01:07 UTC, aahung commented
SQS template cannot be deployed due to some error. To be investigated. So SQS template does not have any integration tests for now.

2021-01-08 20:54 UTC, c2tarun requested changes
Add documentation to the methods missing documentation.

2021-01-08 20:54 UTC, c2tarun commented on nodejs12.x/cookiecutter-aws-sam-hello-nodejs/{{cookiecutter.project_name}}/hello-world/tests/integration/test-api-gateway.js
> +const getStackName = () => {
documentation.

2021-01-08 20:54 UTC, c2tarun commented on nodejs12.x/cookiecutter-aws-sam-step-functions-sample-app/{{cookiecutter.project_name}}/integration-tests/test-state-machine.js
> +const getAndVerifyStackName = async () => {
documentation

2021-01-08 21:32 UTC, aahung commented
> Add documentation to the methods missing documentation.

All resolved.

2021-01-11 17:23 UTC, hoffa approved these changes

2021-01-11 17:33 UTC, c2tarun approved these changes

2021-01-11 18:14 UTC, merged